services:
   itm.file.preview.subscriber:
      class: ITM\FilePreviewBundle\EventListener\FileSubscriber
      arguments: [@service_container]
      tags:
          - { name: doctrine.event_subscriber }

   itm.file.preview.path.resolver:
       class: ITM\FilePreviewBundle\Resolver\PathResolver
       arguments: [@service_container]

   itm.file.preview.form_file_type:
       class: ITM\FilePreviewBundle\Form\Type\FilePreviewType
       arguments: [@service_container]
       tags:
           - { name: form.type, alias: itm_file_preview }
